### ISSUE TITLE
这个想法很流弊

### ISSUE THREAD

**Issue by peach-djf** [WrBug/dumpDex#1]
Class dex = Class.forName("com.android.dex.Dex");
        this.getBytesMethod = dex.getDeclaredMethod("getBytes");
        this.getDexMethod = Class.forName("java.lang.Class").getDeclaredMethod("getDex");

 private String[] packages = {"com.stub.StubApp", "s.h.e.l.l.S"};

这2个包名是啥，？我成功把360最新的普通壳脱了

**Comment by WrBug** [comment]
packages . 是一些加固应用的包名。com.stub.StubApp是360的，s.h.e.l.l.S是爱加密。其他会陆续添加进去

**Comment by peach-djf** [comment]
也就是后面的，各种加固，都逃不过getBytes，这个返回的字节数组，里面就是具体的dex了？希望大神继续开源，膜拜

**Comment by WrBug** [comment]
android8把dex去掉了。我要看看c++那边的处理，估计xposed无能为力了
