### ISSUE TITLE
请问大神用的哪个模拟器,我用mumu模拟器脱腾讯壳不成功

### ISSUE THREAD

**Issue by yizeliang** [WrBug/dumpDex#10]

**Comment by WrBug** [comment]
#5

**Comment by yizeliang** [comment]
我想大神你可能误解我得意思了,,我刚才借了个手机,手机上就能dump出来dex文件,但是在模拟器上不行,想问下大神用的哪款模拟器,,毕竟没有真机,,不能每次都借,,还瞎捣鼓,也挺不好意思的=.=
