### ISSUE TITLE
360jiagu 北京交警无法dump 启动应用闪退

### ISSUE THREAD

**Issue by hello-earth** [WrBug/dumpDex#11]
04-08 11:32:47.460 7155-7155/? A/art: art/runtime/indirect_reference_table.cc:98] JNI ERROR (app bug): local reference table overflow (max=512)

04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292] Runtime aborting...
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292] Aborting thread:
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292] "main" prio=5 tid=1 Runnable
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   | group="" sCount=0 dsCount=0 obj=0x740bc000 self=0xf4c27800
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   | sysTid=7155 nice=0 cgrp=default sched=0/0 handle=0xf73dcd34
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   | state=R schedstat=( 0 0 0 ) utm=2 stm=1 core=3 HZ=100
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   | stack=0xff010000-0xff012000 stackSize=8MB
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   | held mutexes= "abort lock" "mutator lock"(shared held)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   native: #00 pc 00004e64  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   native: #01 pc 00003665  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   native: #02 pc 0025b9c1  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+84)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   native: #03 pc 0023e8e7  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+158)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   native: #04 pc 0022dda1  /system/lib/libart.so (art::AbortState::DumpThread(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, art::Thread*)+32)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   native: #05 pc 0022e00b  /system/lib/libart.so (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+354)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   native: #06 pc 0022e203  /system/lib/libart.so (art::Runtime::Abort()+82)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   native: #07 pc 000a7bc1  /system/lib/libart.so (art::LogMessage::~LogMessage()+1360)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   native: #08 pc 0016211f  /system/lib/libart.so (art::IndirectReferenceTable::Add(unsigned int, art::mirror::Object*)+274)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   native: #09 pc 00298651  /system/lib/libart.so (art::BuildQuickArgumentVisitor::Visit()+56)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   native: #10 pc 0029cef9  /system/lib/libart.so (artQuickProxyInvokeHandler+1104)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   native: #11 pc 000a35cd  /system/lib/libart.so (art_quick_proxy_invoke_handler+12)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   native: #12 pc 0000015c  ???
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   at java.lang.ClassLoader.loadClass [XposedHooked](<Xposed>:514)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   at java.lang.ClassLoader.loadClass [XposedOriginal](ClassLoader.java:504)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative!(Native method)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   at java.lang.ClassLoader.loadClass [XposedHooked](<Xposed>:514)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   at java.lang.ClassLoader.loadClass [XposedOriginal](ClassLoader.java:504)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative!(Native method)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   at java.lang.ClassLoader.loadClass [XposedHooked](<Xposed>:514)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-08 11:32:47.690 7155-7155/? A/art: art/runtime/runtime.cc:292]   at com.wrbug.dumpdex.XposedInit$1.afterHookedMethod(XposedInit.java:69)

**Comment by WrBug** [comment]
设备系统信息提供下

**Comment by hello-earth** [comment]
魅族pro5  android5.1
使用drizzleDumper正常脱壳
