### ISSUE TITLE
请求各位编译成功后给我发一份Apk

### ISSUE THREAD

**Issue by Zxlusersjly** [WrBug/dumpDex#16]
作者提供的链接中下载的Apk无lib文件，感谢。

**Comment by BackTrackCRoot** [comment]
安装后就有了 就在程序目录中

**Comment by Kractal** [comment]
/data/data/com.wrbug.dumpdex目录下是空的，没有任何文件或子目录。请问是在下找错目录了吗？

**Comment by Kractal** [comment]
@Zxlusersjly 陌生的朋友，你的github profile里没有联系方式，请提供一个联系方式吧，我刚刚编译好。

**Comment by Zxlusersjly** [comment]
@Kractal 感谢，我的邮箱是zxluser@foxmail.com

**Comment by Kractal** [comment]
@Zxlusersjly 两个分支各编译一份以附件形式发送至你的邮箱，请查收，如果没有收到请到邮箱的垃圾桶里找找看。此外，能否将develop分支在你的测试环境下的运行结果告知在下？我的测试环境下运行出了问题，目前我无法更换测试环境，希望换个环境看看问题是否还会出现。

**Comment by Zxlusersjly** [comment]
@Kractal 已收到并用邮件回复了，请查看，感谢。

**Comment by BackTrackCRoot** [comment]
你好 @Kractal 您的apk没有编译那两个lib 不知道您的NDK安装是否正常？
![20180501003039](https://user-images.githubusercontent.com/4964761/39438504-fce58242-4cd6-11e8-92d7-f5496ce679e2.png)
这是和我之前编译的对比图，有时间我编译一份新版的。
