### ISSUE TITLE
Windows 上怎么编译，谢谢！

### ISSUE THREAD

**Issue by Sabirjan** [WrBug/dumpDex#26]
Windows 上编译，出错。NDK最新版
7 warnings generated.
FAILED: D:\AndroidStudio\SDK\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe  --target=x86_64-none-linux-android --gcc-toolchain=D:/AndroidStudio/SDK/ndk-bundle/toolchains/x86_64-4.9/prebuilt/windows-x86_64 --sysroot=D:/AndroidStudio/SDK/ndk-bundle/sysroot -DnativeDump_EXPORTS  -isystem D:/AndroidStudio/SDK/ndk-bundle/sysroot/usr/include/x86_64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/nativeDump.dir/src/main/cpp/inlineHook.c.o -MF CMakeFiles\nativeDump.dir\src\main\cpp\inlineHook.c.o.d -o CMakeFiles/nativeDump.dir/src/main/cpp/inlineHook.c.o   -c C:\Users\admin\Documents\AndroidStudio\dumpDex-develop\app\src\main\cpp\inlineHook.c
In file included from C:\Users\admin\Documents\AndroidStudio\dumpDex-develop\app\src\main\cpp\inlineHook.c:19:
D:/AndroidStudio/SDK/ndk-bundle/sysroot/usr/include\arm-linux-androideabi/asm/ptrace.h:21:10: fatal error: 'asm/hwcap.h' file not found
#include <asm/hwcap.h>

**Comment by Sabirjan** [comment]
解决了，谢谢

**Comment by mcpan** [comment]
如何解决的? 同问

**Comment by Sabirjan** [comment]
arm CPU 去掉就可以啦 ，留下 v7和64位的CPU。不知道你遇到的问题是不跟我一样

**Comment by mcpan** [comment]
#28 解决了
