### ISSUE TITLE
WIN10 下无法编译! AS3.1.2 NDK 17.0.4754217

### ISSUE THREAD

**Issue by mcpan** [WrBug/dumpDex#28]
> Android Studio 3.1.2
Windows 10 10.0
NDK 17.0.4754217

> Build command failed.
Error while executing process C:\Users\aaa\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\Users\aaa\Desktop\ld\dumpDex-develop\app\.externalNativeBuild\cmake\debug\x86_64 --target nativeDump}
[1/8] Building C object CMakeFiles/nativeDump.dir/src/main/cpp/dlopen.c.o
[2/8] Building C object CMakeFiles/nativeDump.dir/src/main/cpp/inlineHook.c.o
[3/8] Building CXX object CMakeFiles/nativeDump.dir/src/main/cpp/native.cpp.o
[4/8] Building CXX object CMakeFiles/nativeDump.dir/src/main/cpp/util/fileutils.cpp.o
[5/8] Building CXX object CMakeFiles/nativeDump.dir/src/main/cpp/And64InlineHook.cpp.o
[6/8] Building C object CMakeFiles/nativeDump.dir/src/main/cpp/relocate.c.o
[7/8] Building CXX object CMakeFiles/nativeDump.dir/src/main/cpp/util/deviceutils.cpp.o
FAILED: C:\Users\aaa\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe  --target=x86_64-none-linux-android --gcc-toolchain=C:/Users/aaa/AppData/Local/Android/Sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/windows-x86_64 --sysroot=C:/Users/aaa/AppData/Local/Android/Sdk/ndk-bundle/sysroot -DnativeDump_EXPORTS  -isystem C:/Users/aaa/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include/x86_64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/nativeDump.dir/src/main/cpp/inlineHook.c.o -MF CMakeFiles\nativeDump.dir\src\main\cpp\inlineHook.c.o.d -o CMakeFiles/nativeDump.dir/src/main/cpp/inlineHook.c.o   -c C:\Users\aaa\Desktop\ld\dumpDex-develop\app\src\main\cpp\inlineHook.c
In file included from C:\Users\aaa\Desktop\ld\dumpDex-develop\app\src\main\cpp\inlineHook.c:19:
C:/Users/aaa/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include\arm-linux-androideabi/asm/ptrace.h:21:10: fatal error: 'asm/hwcap.h' file not found
#include <asm/hwcap.h>
         ^~~~~~~~~~~~~
1 error generated.

**Comment by wangkunlin** [comment]
我的也编译不通过，使用 百度云下载的 apk 里面的 so 是 64 的，但是我要dump 的是 32 的程序，加载失败。过不去了

**Comment by mcpan** [comment]
我是这样解决的 

[build.gradle](https://github.com/WrBug/dumpDex/blob/develop/app/build.gradle) 注释的 ndk abiFilters 取消注释 改为
`        ndk {
            abiFilters "armeabi-v7a","arm64-v8a"
        }`

[CMakeLists.txt](https://github.com/WrBug/dumpDex/blob/develop/app/CMakeLists.txt) 后面增加

> if(${ANDROID_ABI} STREQUAL "armeabi-v7a")
	include_directories(${ANDROID_SYSROOT}/usr/include/arm-linux-androideabi)
elseif(${ANDROID_ABI} STREQUAL "arm64-v8a")
	include_directories(${ANDROID_SYSROOT}/usr/include/aarch64-linux-android)
else()
	include_directories(${ANDROID_SYSROOT}/usr/include/x86_64-linux-android)
endif()

**Comment by wangkunlin** [comment]
[参考链接](https://www.jianshu.com/p/27f98165d73d)
