### ISSUE TITLE
ClassNotFoundException: Didn't find class "com.wrbug.dumpdex.XposedInit" 

### ISSUE THREAD

**Issue by chusong** [WrBug/dumpDex#4]
大佬看下怎么回事？新加了一个应用的包名加到packages字段里，打包安装之后出现这个异常
java.lang.ClassNotFoundException: Didn't find class "com.wrbug.dumpdex.XposedInit" on path: DexPathList[[zip file "/data/app/com.wrbug.dumpdex-1/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]

**Comment by WrBug** [comment]
你把包解压出来。看看有没有com.wrbug.dumpdex.XposedInit文件。推荐先generate再安装

**Comment by chusong** [comment]
不知道什么鬼原因它确实没有打包上去，搞了一下弄好了，谢谢
