### ISSUE TITLE
armeabi-v7a做32位so，"/data/local/tmp/libnativeDump64.so" is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by 404div** [WrBug/dumpDex#40]
您好，麻烦请问一下
因为我这里使用的是ndk-17.1.4828580版本（尝试降级，结果一大堆问题），已经移除了对armeabi的支持，我用armeabi-v7a做32位so，arm64-v8a做64位so，
编译后运行 提示以下错误--
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/local/tmp/libnativeDump64.so" is 64-bit instead of 32-bit
讲道理，这个的确应该是64位so，但是如果他寻找32位so不应该去找armeabi-v7a生成的so吗
或者是我别的哪里有问题，麻烦指导一下叻，谢谢

**Comment by WrBug** [comment]
检查下是不是把32和64弄反了

**Comment by electric009** [comment]
我也遇到这问题了  楼主解决了吗

**Comment by 404div** [comment]
我对调32和64以后，报另外一个错误：
couldnt map  “/data/local/tmp/libnativeDump64.so” segment 1: permission denied!
![image](https://user-images.githubusercontent.com/28550842/44763681-e457fa00-ab7e-11e8-9e56-c8b62e4ac742.png)
已经修改权限为777。
请问是什么问题啊？
好懵逼哦！ 
@WrBug 麻烦解答一下，谢谢啦！

**Comment by electric009** [comment]
我对调以后 也是报这错  望作者 帮指点一下哈

**Comment by electric009** [comment]
难道是对64位支持不够好吗？@WrBug

**Comment by electric009** [comment]
@404div  哥们 你解决了吗 我也卡在这了 要不 咱两个加qq一起研究研究？？？？

**Comment by electric009** [comment]
@WrBug 是不是 64位手机 只能脱64位的apk的壳？要想脱32位的壳 只能用32位手机？？？

**Comment by WrBug** [comment]
检查下目录权限，调试下应用能否读取so文件

**Comment by electric009** [comment]
解决这个问题了

**Comment by 404div** [comment]
@electric009 啊哈哈哈哈，大兄弟，怎么解决的，我还是没解决啊

**Comment by h080294** [comment]
是小米的手机么，检查一下SELinux权限，如果Enforcing的话，临时设置成0 （Permissive）

**Comment by 404div** [comment]
@h080294 
是的，是的，就是这样。。。。
谢谢哈。。。
虽然 到最后发现遇到反调试了。。。。

@WrBug 
请问楼主，有没有遇到过这种情况，xposed的hook方法成功，但是不执行hook代码？
应该是已经hook到了方法----
——（首先hook方法没报错，jdb动态methods能看到带有xposed标签的重载）
其次，被hook的方法确实执行了——
——jdb动态触发了该方法的断点

————但是，但是，到最后，我自己的hook代码没有执行，即便只是简单地log打印
请问，有没有人遇到过这种情况?是为什么呢？
有人说是app检测了xposed并通过反射关闭了xposed，具体不太理解，能解释一下吗？
