### ISSUE TITLE
编译不通过，看了有人勾选了CMake,我也下载并安装CMake并且勾选了，但是还是报这个问题

### ISSUE THREAD

**Issue by DemonArrow** [WrBug/dumpDex#50]
Error occurred while communicating with CMake server. Check log /dumpDex-master/app/.externalNativeBuild/cmake/debug/armeabi-v7a/cmake_server_log.txt for additional information.

**Comment by ananas-xxj** [comment]
解决没

**Comment by zhentianjue** [comment]
i again this proquestions

**Comment by aislient** [comment]
没有编译这个项目，但是在自己的NDK程序，省级cmake后出现该问题，升级最新的Android studio 与NDK gradle解决问题。

**Comment by zhentianjue** [comment]
thank you very much

**Comment by ananas-xxj** [comment]
> 没有编译这个项目，但是在自己的NDK程序，省级cmake后出现该问题，升级最新的Android studio 与NDK gradle解决问题。
as最新版是用的稳定版还是canary版

**Comment by ananas-xxj** [comment]
@gcgongchao as 最新版是稳定版还是canary版

**Comment by aislient** [comment]
@ananas-xxj 全部最新了，as 3.3

**Comment by hfutgl** [comment]
@gcgongchao 我的as是3.3 但是依然有问题

**Comment by aislient** [comment]
@hfutgl as、gradle、cmake、ndk都更到最新。

**Comment by hfutgl** [comment]
@gcgongchao  gradle修改成3.3 可以了

**Comment by hfutgl** [comment]
gradle 3.3.0

**Comment by CSnowStack** [comment]
@hfutgl  grade 3.3.0 AS 3.3.1  ndk r16b , cmake 3.10.2编译不了

**Comment by dogfenglee** [comment]
me to change gradle to 3.3

**Comment by dogfenglee** [comment]
dependencies {
        classpath 'com.android.tools.build:gradle:3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

**Comment by wwb312429** [comment]
studio   ndk  gradle 全部更新到最新版本，解决问题。

**Comment by lipin0905** [comment]
最新具体是什么版本 呀，亲们。心好累，这个问题已经困扰了两天时间了。。。。。

**Comment by wwb312429** [comment]
升级最新的Android studio 与NDK gradle解决问题。

**Comment by echooo10** [comment]
https://www.jianshu.com/p/cde0c78683de 
我是用这个才解决的，装成CMake旧版本就可以了
