### ISSUE TITLE
 'arm-linux-androideabi/asm/ptrace.h' file not found

### ISSUE THREAD

**Issue by wlianghe00** [WrBug/dumpDex#8]
编译时 报错'arm-linux-androideabi/asm/ptrace.h' file not found

**Comment by WrBug** [comment]
https://www.jianshu.com/p/27f98165d73d

**Comment by wlianghe00** [comment]
![image](https://user-images.githubusercontent.com/3353880/38067858-cb5ce27e-3340-11e8-9c68-cf997f4f57ae.png)
咋在saveData这里报错呢

**Comment by WrBug** [comment]
真机上跑
